[CmdletBinding()]
param(
    [string]$DshRoot,
    [switch]$NoOpen,
    [switch]$GenerateOnly
)

$ErrorActionPreference = 'Stop'
$projectRoot = [System.IO.Path]::GetFullPath($PSScriptRoot)

function Find-DshRoot {
    param([string]$Requested)
    $parent = Split-Path -Parent $projectRoot
    $candidates = @(
        $Requested,
        $env:DSH_ROOT,
        (Join-Path $parent 'DeepSeek-Harness'),
        'D:\DeepSeek-Harness',
        (Join-Path $HOME 'DeepSeek-Harness'),
        (Join-Path $HOME 'source\repos\DeepSeek-Harness')
    ) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }

    foreach ($candidate in $candidates) {
        $full = [System.IO.Path]::GetFullPath($candidate)
        $package = Join-Path $full 'package.json'
        if (-not (Test-Path -LiteralPath $package)) { continue }
        try {
            $metadata = Get-Content -LiteralPath $package -Raw -Encoding UTF8 | ConvertFrom-Json
            if ($metadata.name -eq '@deepseek-ai/dsh-root') { return $full }
        } catch { }
    }
    throw '没有找到 DSH 源码目录。请使用 -DshRoot "D:\你的路径\DeepSeek-Harness" 指定。'
}

function Yaml-Path([string]$Path) {
    $full = [System.IO.Path]::GetFullPath($Path)
    $forward = $full -replace '\\', '/'
    return $forward -replace "'", "''"
}

$resolvedDshRoot = Find-DshRoot $DshRoot
$rootYaml = Yaml-Path $projectRoot
$stateYaml = Yaml-Path (Join-Path $projectRoot 'bridge\dsh-plugin.mjs')
$serverYaml = Yaml-Path (Join-Path $projectRoot 'bridge\mcp-server.mjs')
$healthYaml = Yaml-Path (Join-Path $projectRoot 'bridge\dsh-health-v04.mjs')
$overlayDirectory = Join-Path $env:LOCALAPPDATA 'WhaleAlive\DSH'
$overlayPath = Join-Path $overlayDirectory 'whale-alive.cordis.yml'
$overlay = @"
# Generated by Whale Alive. Re-run Connect-DSH.cmd after moving this folder.
- insert:
    - id: whale-alive-state
      name: '$stateYaml'
    - id: whale-alive-mcp
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: whale_alive
        transport: stdio
        command: node
        args: ['$serverYaml']
        cwd: '$rootYaml'
        toolCallTimeoutMs: 600000
    - id: whale-alive-health
      name: '$healthYaml'
"@
New-Item -ItemType Directory -Path $overlayDirectory -Force | Out-Null
[System.IO.File]::WriteAllText($overlayPath, $overlay, [System.Text.UTF8Encoding]::new($false))
Write-Host "Whale Alive overlay: $overlayPath"
Write-Host "DSH directory: $resolvedDshRoot"
if ($GenerateOnly) { return }

foreach ($command in @('node', 'npm', 'pnpm')) {
    if (-not (Get-Command $command -ErrorAction SilentlyContinue)) {
        throw "缺少 $command。DSH 需要 Node.js 22.19+ 和 pnpm；安装后重新运行本脚本。"
    }
}

$sdk = Join-Path $projectRoot 'node_modules\@modelcontextprotocol\sdk'
if (-not (Test-Path -LiteralPath $sdk)) {
    Write-Host '首次接入：正在安装 Whale Alive MCP 依赖…'
    Push-Location $projectRoot
    try {
        & npm.cmd ci --omit=dev
        if ($LASTEXITCODE -ne 0) { throw 'npm ci 执行失败。' }
    } finally { Pop-Location }
}

& (Join-Path $projectRoot 'Start-WhaleAlive.ps1')
Write-Host '正在使用 Whale Alive overlay 启动 DSH；关闭此窗口会结束当前 DSH Web 进程。'
Push-Location $resolvedDshRoot
try {
    $arguments = @('dsh', 'web', '--patch', $overlayPath)
    if ($NoOpen) { $arguments += '--no-open' }
    & pnpm.cmd @arguments
    exit $LASTEXITCODE
} finally { Pop-Location }
